services:
  nginx:
    restart: unless-stopped
    build:
      target: nginx-prod
      context: ./web
    image: ghcr.io/equinor/mercury-nginx
    ports:
      - "80:8080"

  api:
    image: ghcr.io/equinor/mercury-api
    restart: unless-stopped
    build:
      context: api
      cache_from:
        - ghcr.io/equinor/mercury-api:latest
      args:
        LIBHG_VERSION: $LIBHG_VERSION
      secrets:
        - libhg-pat

secrets:
  libhg-pat:
    environment: "LIBHG_PAT"
