name: "Linting and checks"
on:
  # Workflow dispatch is used for manual triggers
  workflow_dispatch:
  # Workflow call is used for called from another workflow
  workflow_call:

permissions:
  contents: read

jobs:
  prek:
    runs-on: ubuntu-latest
    name: "Linting and checks: Pre-commit"
    steps:
      - name: "Setup: Checkout repository"
        uses: actions/checkout@v6

      - name: "Run: Pre-commit with prek"
        uses: j178/prek-action@v1

  mypy:
    runs-on: ubuntu-latest
    name: "Linting and checks: Mypy static type check"
    steps:
      - name: "Setup: Checkout repository"
        uses: actions/checkout@v6
        with:
          sparse-checkout: api

      - name: "Setup: Install uv"
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: "Setup: Install python dependencies"
        run: uv sync --locked --dev
        working-directory: api

      - name: "Run: Static type check with mypy"
        run: uv run mypy src
        working-directory: api

  typescript-compile:
    runs-on: ubuntu-latest
    name: "Linting and checks: Typescript compile"
    steps:
      - name: "Setup: Checkout repository"
        uses: actions/checkout@v6
        with:
          sparse-checkout: web

      - name: "Setup: Install node"
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: web/yarn.lock

      - name: "Setup: Install node dependencies"
        run: yarn install --frozen-lockfile
        working-directory: web

      - name: "Run: Compile with yarn"
        run: yarn compile
        working-directory: web
