name: "Release new prod version"
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      release-tag:
        description: "release tag"
        required: true
        type: string
    secrets:
      LIBHG_PAT:
        description: "PAT for accessing libhg repository"
        required: true

jobs:
  publish-release-image:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/publish-images.yaml
    with:
      image-tags: ${{ inputs.release-tag }}
      applicationinsights-connection-string: ${{ vars.APP_INSIGHT_CON_STRING_PROD }}
    secrets:
      LIBHG_PAT: ${{ secrets.LIBHG_PAT }}

  deploy-prod-to-radix:
    needs: publish-release-image
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/deploy-to-radix.yaml
    with:
      image-tag: ${{ inputs.release-tag }}
      radix-environment: prod
